# Generated by Django 2.0.2 on 2018-02-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('secret', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('apimodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feelings.APIModel')),
                ('pet_name', models.CharField(max_length=100)),
            ],
            bases=('feelings.apimodel',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('apimodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feelings.APIModel')),
                ('pet_name', models.CharField(max_length=100)),
                ('anger_inside', models.IntegerField()),
                ('anger_outside', models.IntegerField()),
                ('joy_inside', models.IntegerField()),
                ('joy_outside', models.IntegerField()),
                ('fear_inside', models.IntegerField()),
                ('fear_outside', models.IntegerField()),
                ('disgust_inside', models.IntegerField()),
                ('disgust_outside', models.IntegerField()),
                ('sadness_inside', models.IntegerField()),
                ('sadness_outside', models.IntegerField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete='cascade', related_name='people', to='feelings.Classroom')),
            ],
            bases=('feelings.apimodel',),
        ),
    ]
