# Generated by Django 2.0.2 on 2018-02-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='anger_inside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='anger_outside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='disgust_inside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='disgust_outside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='fear_inside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='fear_outside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='joy_inside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='joy_outside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='sadness_inside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='sadness_outside',
            field=models.IntegerField(default=0),
        ),
    ]
