# Generated by Django 2.0.2 on 2018-02-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0002_auto_20180228_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
